//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeusServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAT1FILE
    {
        public long PATCODE { get; set; }
        public string PATLAST { get; set; }
        public string PATFIRST { get; set; }
        public string PATLATIN { get; set; }
        public Nullable<System.DateTime> PATBIRTH { get; set; }
        public string PATSEX { get; set; }
        public string PATPROFF { get; set; }
        public string PATADDR { get; set; }
        public string PATZIP { get; set; }
        public string PATTOWN { get; set; }
        public string PATPHON { get; set; }
        public Nullable<int> PATFAX { get; set; }
        public string PATEMAIL { get; set; }
        public string PATAFM { get; set; }
        public string PATADT { get; set; }
        public Nullable<bool> PATCIGAR { get; set; }
        public string CIGARNUM { get; set; }
        public string PATFKIND { get; set; }
        public string PATOPER { get; set; }
        public string PATSICK { get; set; }
        public string PATINHER { get; set; }
        public string PATATHL { get; set; }
        public Nullable<short> PATEKPT { get; set; }
        public Nullable<bool> SENSENT { get; set; }
        public string PATALLERGY { get; set; }
        public Nullable<short> PATANAEMIAID { get; set; }
        public Nullable<short> PATDISEASEID { get; set; }
        public string PATBLTYPE { get; set; }
        public string PATRHES { get; set; }
        public Nullable<bool> NURSED { get; set; }
        public Nullable<float> XREWSEIS { get; set; }
        public Nullable<float> PISTWSEIS { get; set; }
        public Nullable<bool> SENTRANS { get; set; }
        public Nullable<short> PATKAT { get; set; }
        public int SAPPATCODE { get; set; }
        public Nullable<int> DOYCODE { get; set; }
        public Nullable<bool> WEB { get; set; }
        public Nullable<System.DateTime> WEBDATE { get; set; }
        public string WEBPASS { get; set; }
        public string AMKA { get; set; }
        public Nullable<int> TOWNCODE { get; set; }
        public string CTRCODE { get; set; }
        public string CTRCODE_ST { get; set; }
        public string PATPASS { get; set; }
        public string PATMOBILE { get; set; }
        public string PROFFCODE { get; set; }
        public Nullable<int> TAMCODE1 { get; set; }
        public Nullable<int> TAMCODE2 { get; set; }
        public Nullable<System.DateTime> LASTHISTDT { get; set; }
        public Nullable<short> TAMCODE { get; set; }
    }
}
